---
- name: Copy files
  become: true
  copy:
    src: ~/project/.circleci/ansible/deploy/files/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: Unarchive
  become: true
  shell: |
    cd /home/ubuntu
    tar -xvzf artifact.tar.gz

- name: start web server
  become: true
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start

# - name: start web server
#   become: true
#   shell: |
#     cd ~/backend-app/dist
#     pm2 stop default
#     pm2 start main.js -f
