---
- name: start web server
  become: true
  shell: |
    tar -xvzf ~/project/.circleci/ansible/deploy/files/artifact.tar.gz
    echo "content of main.js ---"
    cat ./dist/main.js
    npm install
    pm2 stop default
    pm2 start ./dist/main.js -f
